### ISSUE TITLE
Sometimes when you die in the first few percent of the level, the effect stops working, only the w speed part works

### ISSUE THREAD

**Issue by congregationn** [DeepRsnanceX/YoutubeShortsEdit#2]

**Comment by DeepRsnanceX** [comment]
okay hold on i'm gonna need some more info

- Any example levels where you've had it happen?
- Do you manually reset while/after dying?
- Do you manually pause before/while/after dying?

In any case, pausing and then unpausing SHOULD fix it if it's no longer working.

**Comment by congregationn** [comment]
some levels it happened on: shardscapes, deadlocked, checked steam, 10hex
no i don't manually reset
no i dont pause
it doesn't fix it

Basically it works once but after that it just stops and i have to reopen it
on further playing though it seems like on these levels its not only if you die in the first few percent but it just stops working after 1 death

**Comment by DeepRsnanceX** [comment]
released v1.0.1, lmk if it fixes it

**Comment by Asterveila** [comment]
closing due to inactivity
